/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keaven_android_base_jni_StringKit */

#ifndef _Included_com_keaven_android_base_jni_StringKit
#define _Included_com_keaven_android_base_jni_StringKit
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
