/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keaven_android_base_jni_MathKit */

#ifndef _Included_com_keaven_android_base_jni_MathKit
#define _Included_com_keaven_android_base_jni_MathKit
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
